name: QuickHold-iOS
options:
  bundleIdPrefix: com.quickvault
  deploymentTarget:
    iOS: "17.0"
  developmentLanguage: zh-Hans

packages:
  QuickHoldKit:
    path: ../QuickHoldKit

targets:
  QuickHold-iOS:
    type: application
    platform: iOS
    deploymentTarget: "17.0"

    sources:
      - path: QuickHold-iOS
        excludes:
          - "*.md"
          - "todo_delete"

    settings:
      base:
        PRODUCT_NAME: QuickHold
        PRODUCT_BUNDLE_IDENTIFIER: com.codans.quickvault.ios
        INFOPLIST_FILE: QuickHold-iOS/Resources/Info.plist
        CODE_SIGN_ENTITLEMENTS: QuickHold-iOS/Resources/QuickHold.entitlements
        CODE_SIGN_STYLE: Automatic
        CODE_SIGN_IDENTITY: "-"
        IPHONEOS_DEPLOYMENT_TARGET: "17.0"
        SWIFT_VERSION: "5.9"
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        TARGETED_DEVICE_FAMILY: "1,2"
        SUPPORTS_MACCATALYST: NO
        DEVELOPMENT_TEAM: ""

    dependencies:
      - package: QuickHoldKit
        product: QuickHoldCore
      - sdk: UIKit.framework
      - sdk: SwiftUI.framework
      - sdk: Security.framework
      - sdk: LocalAuthentication.framework

    scheme:
      testTargets:
        - QuickHold-iOSTests
      gatherCoverageData: true

    prebuildScripts:
      - script: |
          echo "Building QuickHold iOS App"
        name: "Pre-build Info"
        basedOnDependencyAnalysis: false

  QuickHold-iOSTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - QuickHold-iOSTests
    dependencies:
      - target: QuickHold-iOS
      - package: QuickHoldKit
        product: QuickHoldCore
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.quickvault.ios.tests
        IPHONEOS_DEPLOYMENT_TARGET: "17.0"
