name: QuickVault-iOS
options:
  bundleIdPrefix: com.quickvault
  deploymentTarget:
    iOS: "17.0"
  developmentLanguage: zh-Hans

packages:
  QuickVaultKit:
    path: ../QuickVaultKit

targets:
  QuickVault-iOS:
    type: application
    platform: iOS
    deploymentTarget: "17.0"

    sources:
      - path: QuickVault-iOS
        excludes:
          - "*.md"

    settings:
      base:
        PRODUCT_NAME: QuickVault
        PRODUCT_BUNDLE_IDENTIFIER: com.quickvault.ios
        INFOPLIST_FILE: QuickVault-iOS/Resources/Info.plist
        CODE_SIGN_ENTITLEMENTS: QuickVault-iOS/Resources/QuickVault.entitlements
        CODE_SIGN_STYLE: Automatic
        CODE_SIGN_IDENTITY: "-"
        IPHONEOS_DEPLOYMENT_TARGET: "17.0"
        SWIFT_VERSION: "5.9"
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        TARGETED_DEVICE_FAMILY: "1,2"
        SUPPORTS_MACCATALYST: NO
        DEVELOPMENT_TEAM: ""

    dependencies:
      - package: QuickVaultKit
        product: QuickVaultCore
      - sdk: UIKit.framework
      - sdk: SwiftUI.framework
      - sdk: Security.framework
      - sdk: LocalAuthentication.framework

    scheme:
      testTargets:
        - QuickVault-iOSTests
      gatherCoverageData: true

    prebuildScripts:
      - script: |
          echo "Building QuickVault iOS App"
        name: "Pre-build Info"
        basedOnDependencyAnalysis: false

  QuickVault-iOSTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - QuickVault-iOSTests
    dependencies:
      - target: QuickVault-iOS
      - package: QuickVaultKit
        product: QuickVaultCore
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.quickvault.ios.tests
        IPHONEOS_DEPLOYMENT_TARGET: "17.0"
